### ISSUE TITLE
SecurityTrails.com isn't responding the way we want to, skipping . . .

### ISSUE THREAD

**Issue by rxl75166** [juuso0/CDNRECON#1]
securitytrails.com url isn't responding the way we want to, skipping . . .

After add api in the URL now working fine-
try:
        RESPONSE = requests.get("https://api.securitytrails.com")
        STATUS_CODE = RESPONSE.status_code

**Comment by juuso0** [comment]
Seems like the securitytrails homepage has a more aggressive captcha now which is likely the issue. Thanks for the heads up, i'll change it to api.securitytrails.com as soon as possible.
